#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
MINECRAFT_VERSION=1.11.2
MINECRAFT_JAR=${SCRIPT_DIR}/minecraft/bin/minecraft_server.${MINECRAFT_VERSION}.jar

rm -rf ${SCRIPT_DIR}/minecraft/data
mkdir -p ${SCRIPT_DIR}/minecraft/bin
mkdir -p ${SCRIPT_DIR}/minecraft/logs

if [ ! -f "${MINECRAFT_JAR}" ]; then
wget https://s3.amazonaws.com/Minecraft.Download/versions/${MINECRAFT_VERSION}/minecraft_server.${MINECRAFT_VERSION}.jar -O ${MINECRAFT_JAR}
fi

cat <<EOF >${SCRIPT_DIR}/minecraft/bin/minecraft-env
# This file is auto-generated by the container.  
export MINECRAFT_VERSION=${MINECRAFT_VERSION}
export MINECRAFT_JAR=/minecraft/bin/minecraft_server.${MINECRAFT_VERSION}.jar
export MINECRAFT_HOME=/minecraft
export MINECRAFT_DATA=/minecraft/data
export MINECRAFT_LOGS=${MINECRAFT_DATA}/logs
EOF

docker build . -t minecraft

docker tag minecraft if6was9/minecraft