---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  labels:
    app: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - name: minecraft
          image: if6was9/minecraft
          volumeMounts:
            - mountPath: /minecraft/data
              name: minecraft-data
          ports:
            - containerPort: 25565
      volumes:
        - name: minecraft-data
          hostPath:
            path: /minecraft/data
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: minecraft
spec:
  type: NodePort
  selector:
    app: minecraft
  ports:
    - port: 25565
      targetPort: 25565
      nodePort: 25565
